---
- name: Rustdesk
  block:
    - name: Scrape URL for latest version
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ user }}/{{ repo }}/releases/latest
        return_content: true
      register: rustdesk_latest

    - name: Split version out
      ansible.builtin.set_fact:
        rustdesk_latest_version: "{{ rustdesk_latest.json.tag_name }}"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Check installed rustdesk version
      ansible.builtin.command: flatpak run com.rustdesk.RustDesk --version
      register: rustdesk_installed_version_output
      ignore_errors: true
      changed_when: true

    - name: Save installed rustdesk version as a fact
      ansible.builtin.set_fact:
        rustdesk_installed_version: "{{ rustdesk_installed_version_output.stdout if rustdesk_installed_version_output.rc == 0 else 'not installed' }}"
      ignore_errors: "{{ ansible_check_mode }}"
      when: rustdesk_installed_version_output is defined

    - name: Display the rustdesk version
      ansible.builtin.debug:
        msg:
          - "installed: {{ rustdesk_installed_version }}"
          - "available: {{ rustdesk_latest_version }}"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Download rustdesk
      ansible.builtin.get_url:
        url: https://github.com/{{ user }}/{{ repo }}/releases/download/{{ rustdesk_latest_version }}/rustdesk-{{ rustdesk_latest_version }}-x86_64.flatpak
        dest: /tmp/rustdesk.flatpak
        mode: '0777'
      ignore_errors: "{{ ansible_check_mode }}"
      when:
        - rustdesk_installed_version != rustdesk_latest_version

    - name: Install rustdesk
      ansible.builtin.command: flatpak install --user --assumeyes /tmp/rustdesk.flatpak
      ignore_errors: "{{ ansible_check_mode }}"
      changed_when: true
      when:
        - rustdesk_installed_version != rustdesk_latest_version
