---
- name: Install
  hosts: steamdeck
  roles:
    - role: steamdeck
  tasks:
    - name: Clone dotfiles
      ansible.builtin.git:
        repo: https://github.com/MyNameIs-13/dotfiles.git
        dest: "{{ __dotfiles_dest }}"
        version: master
